default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.104.0
  hooks:
    - id: terraform_fmt
      args: [--args=-recursive]
    - id: terraform_validate
    - id: terraform_tflint
      args: [--args=--recursive]
    - id: terraform_checkov
    - id: terraform_docs

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--verbose]

- repo: local
  hooks:
    - id: generate-terraform-graph
      name: Generate Terraform resource graph
      entry: bash -c "terraform graph | dot -Tsvg > resource-graph.svg"
      language: system
      pass_filenames: false
      always_run: true

minimum_pre_commit_version: "4.5.1"
